import { mailModule } from '@kernhq/module-mail/server'

/**
 * What this image contains, printed as JSON.
 *
 *   node dist/manifest.js
 *
 * The release feed is generated by asking each published image this question, so what an admin is
 * told a release changes comes from the artefact itself rather than from a list somebody remembered
 * to edit. It touches no database and no network.
 */
console.log(
  JSON.stringify({
    service: 'mail',
    kernVersion: process.env.KERN_VERSION ?? '0.0.0-dev',
    modules: { [mailModule.definition.id]: mailModule.definition.version },
  }),
)
