-- This file once recorded that mail's tables were "intentionally not row-level secured", on the
-- grounds that their workspace_id is nullable and every query filtered by hand. That reasoning did
-- not survive review: a hand-written `where` is one forgotten clause from a workspace reading
-- another's delivery log. `0002_rls.sql` puts a forced policy on every table, admitting a row for
-- its own workspace or for the `'*'` binding the instance-wide paths use. The file stays because a
-- journal entry cannot be removed once instances have applied it.
